### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by mrmartineau** [nicbell/postscss#1]
I've been having some issues with my scss and I'm not sure if it's to do with some broken code or not. Does postscss have any sass error handling, and does it output compilation errors to the console? I don't think it does but if you know of an easy way to add it, it would be very useful.

Cheers mate

**Comment by nicbell** [comment]
It returns a promise. So do promise.catch in your code and you can output the message.

**Comment by mrmartineau** [comment]
Ah great, I added the `catch` like so:

``` js
postscss(plugins).processMany([
    {
        from: scssDir + '/kickoff.scss',
        to: cssDir + '/barilla.css'
    },
    {
        from: scssDir + '/kickoff-old-ie.scss',
        to: cssDir + '/barilla-old-ie.css'
    }
]).then(done).catch(function(error) {
    console.error('\n' + error.formatted + '\n');
});
```

which gives an error like so:

```
Error: Invalid CSS after "...s style text */": expected "}", was "&:focus::-ms-value"
        on line 57 of /assets/src/scss/components/_forms-custom-select.scss
>>  the text to match the focus style text */
   ------------------------------------------^
```

**Comment by mrmartineau** [comment]
Going to add this to Kickoff now :+1:
